### ISSUE TITLE
Bee Modeling: Population Interaction

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#10]
How should populations of bees in a given forest cell interact?  Should there be competition between them?  Does the carrying capacity discussed in #3 affect all the bees collectively, or is there an independent carrying capacity for each bee?

**Comment by jvamosi** [comment]
there are a number of ways you could do this so you can choose according to difficulty level. From an ecosystem service perspective, competition of bees often works to improve pollination. They don't like being in each other's presence so they fly greater distances between plants and this decreases the amount of selfing in the blueberries (which leads to inbreeding depression). So greater abundance and diversity of bees can improve blueberry yield. Normally, each bee species would have its own carrying capacity and it would likely be that the bee with the highest carrying capacity is often the worst pollinator (messy sorts that will visit just about anything) and the species with the lowest carrying capacity is often the best. There would be exceptions to that rule of course but that's the general pattern we see.
