### ISSUE TITLE
Bolaram Paul: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by bolaram** [jvamosi/Diversibee#123]
ecology,agriculture are favorite topics. i am with the motivation about "Natural Idea".<p><br><blockquote>This issue was created by @bolaram via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by cgmb** [comment]
Welcome to the project.
