### ISSUE TITLE
Land Modeling: Maturation

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#14]
Could introduce a parameter per cell that tracks how long a cell has been occupied by a given type (crop or forest).  Crops may become less productive if left in too long (reflecting soil damage and the need for crop rotation), and forest cells may increase their carrying capacity for bees over time as the mature.

**Comment by sookinoby** [comment]
I can add a counter to each cell which tracks the maturation. The counter is updated on each round( when user presses the next button). Is my understanding right?

**Comment by cgmb** [comment]
Within our current levels, there's no longer any concept of the passage of time so it doesn't make sense there. However, I think this is a pretty good idea for part of a future level of the game.
