### ISSUE TITLE
Land Modeling: Forest Structure

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#18]
Currently, forests are only characterized by their carrying capacity for bees.  We could improve this by modeling a forest tile as having 4 different types of plant growth, with the following characteristics:
 - each plant type is a better habitat for a particular one of the four bee species, meaning they will affect the carrying capacities for bee species independently
 - each plant type may increase / decrease as a function of maturation of the forest; for example, a freshly planted forest might be all brush and saplings, while a more mature forest will have taller, more established trees.

**Comment by cgmb** [comment]
This sounds a lot like #14. I like it, but it's not quite clear how it would apply to the game as it currently stands. We should keep it in mind when designing new levels.
