### ISSUE TITLE
Create a spritesheet

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#23]
`img/spriteSheet.png` is the spritesheet for terrain animations:

![spritesheet](https://raw.githubusercontent.com/BillMills/Diversibee/master/img/spriteSheet.png)

Terrain animations consist of 4 frames, each 20x20 px in the spritesheet. The frames are arranged as:

 - first row: grassland animation
 - second row: forest animation
 - third row: blueberry crop animation

We'd like a spritesheet matching this configuration with some attractive animation frames; if feasible, the same spritesheet at a larger size (40x40 and 60x60 px cells) would be nice to have, too.

**Comment by padawin** [comment]
In the branch issue-23-sprites is a suggestion of animated sprites for the trees, blueberries and grass.
Open for discussion ;-)
