### ISSUE TITLE
Land Modeling: Initial forest distribution

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#24]
Currently, `setUpBoardState` initializes the map with a random configuration of forests and grasslands; change this function to create a more realistic distribution of forests.

**Comment by cgmb** [comment]
I quite liked this, though it was removed to give the user a simpler starting state. Perhaps we can bring it back for later levels (or just tone it down in the earlier levels rather than eliminating it).

**Comment by cgmb** [comment]
I don't think there's any immediate work to be done on this, so I'm closing the issue. I'll mark it with brainstorming, though, so people can easily find it if they're trying to think up new ideas for the next levels. That forest generation algorithm was seriously cool.
