### ISSUE TITLE
Ghislain Rodrigues: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by padawin** [jvamosi/Diversibee#27]
Hi,
My name is Ghislain, I would like to use my skills in javascript for this project. I am afraid my help will mostly be technical, but I will be keen to learn also about ecology/bees//environment/... through it.

Ghislain<p><br><blockquote>This issue was created by @padawin via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by jvamosi** [comment]
Welcome aboard! We could use your expertise. Feel free to ask any questions.

**Comment by padawin** [comment]
Hi!

Thanks for the welcome! I went quickly through the code, played a bit with GIMP (cf issue #23).
From the files I saw, there seems to be inconsistencies in the code format (spaces, indentations...) Are there any rules which should be followed? Should we define a grounding of coding guidelines for the code's sake?

**Comment by cgmb** [comment]
That's a good idea. I've moved the repo to using the airbnb coding guidelines. The style is checked by [JSCS](http://jscs.info/overview.html) as a part of the CI build.
