### ISSUE TITLE
Think about incorporating a bee 'carrying capacity' (max sustainable bee pop. size) for each cell

### ISSUE THREAD

**Issue by netthinker** [jvamosi/Diversibee#3]
The carrying capacity for a forest cell could be influenced by the number of other adjacent forest cells. Crop cells could also have very small carrying capacities so that they support a very small # of bees.

**Comment by cgmb** [comment]
This more detailed model might be better suited for later levels. We plan to strip down the model complexity significantly in the early stages of the game.
