### ISSUE TITLE
Jacob Tomlinson: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by jacobtomlinson** [jvamosi/Diversibee#31]
My name is Jacob, I am a Python/JavaScript developer who can chip in from a technical point of view and I also have a couple of graphic designers with me who are keen to help.<p><br><blockquote>This issue was created by @jacobtomlinson via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by padawin** [comment]
Hi Jacob,

I am connected on IRC, we can chat and see where to go on that.

Ghislain
