### ISSUE TITLE
Add some basic styling

### ISSUE THREAD

**Issue by jacobtomlinson** [jvamosi/Diversibee#32]
It would be good to add some basic css to the page. Probably easiest to start with bootstrap and add a but of custom css too.

**Comment by jacobtomlinson** [comment]
To stick with the idea of simplicity and using 'pure' code without too many libraries I think I'mm just use css reset instead of bootstrap and work from there.

**Comment by ChrissiQ** [comment]
Yeah, since this is a canvas game I don't imagine we'll need a CSS framework for quite awhile, as there are more important things to deal with than the page design.

**Comment by cgmb** [comment]
@ChrissiQ did some work on page styling. If you have suggestions for further improvements, maybe we can add them to the list in Issue #48.
