### ISSUE TITLE
Create a gh-pages branch

### ISSUE THREAD

**Issue by ajspadial** [jvamosi/Diversibee#33]
This is Antonio from Spain. I'm a Research Software Engineer with some experience in ecology and environment, and very kin on games.

Have you considerate to create a `gh-pages` branch replicating the master branch? If you do so the game would become playable from its own **git hub site**

I'm not sure I could do that in a PR

**Comment by jacobtomlinson** [comment]
:+1:

**Comment by padawin** [comment]
Good idea!

**Comment by jvamosi** [comment]
Hi! This all sounds good. It's still early here in Calgary but when we've had some coffee, etc. we'll find a way to get in touch (perhaps on Vidyo?)

**Comment by jacobtomlinson** [comment]
@jvamosi we are in https://kiwiirc.com/client/irc.mozilla.org/#diversibee if you want to join us

**Comment by cgmb** [comment]
Good idea! Done.

http://jvamosi.github.io/Diversibee/
