### ISSUE TITLE
Antonio Jesús Sánchez Padial: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by ajspadial** [jvamosi/Diversibee#36]
I'm a Software Engineer with a strong interest in science, ecology, environment and games. I work as a research engineer at INIA a Spanish gov organization for agricultural and forestry research, in Madrid.

You know, this project looks like the kind of thing I can enjoy joining.<p><br><blockquote>This issue was created by @ajspadial via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by jvamosi** [comment]
Awesome. We're gearing up now. Sorry, it must be getting a little late there.
