### ISSUE TITLE
A plan of action

### ISSUE THREAD

**Issue by pwpD1vers1bee** [jvamosi/Diversibee#41]
We (@cgmb,@arowens,@ChrissiQ,@jvamosi,@pwpD1vers1bee,@JeremyAdamHart) are planning to advance the game be first having a minimum working version, than advancing it through “snow balling” (following Agile practices ;-).  

1) We work off the code as it exists at 10 am, MST. The “playing board” is already there, making it possible to define what grows in each square by clicking into it.

2) The first step we are envisioning is to introduce the simplest payoff function (yearly farmer’s profit function) possible.  We are planning to use the function
profit = #blueberry squares x #forest squares .
This has the property that the farmer’s profit is 0 when there are no blueberries, and it is also 0 when there is no forest (and thus no bees), and is greater than 0 somewhere in-between (no wonder, as the profit can be re-expressed as a square function of the number of blueberry squares:

profit = # blueberry squares x (total number of squares - #blueberry squares).

It thus introduces, in the simplest form, a tradeoff between having blueberries and having forest, which is essential to the message of the game, the promotion of diversity.

3) Once this is done (making perhaps a playable game for 4-year olds), we plan to gradually introduce more interesting profit functions.  This could happen by moving in three directions:
- Introducing spatial effects (e.g., a consolidated forest can support more bees, but a fragmented forest of the same area may reduce the maximum distance between the blueberries and the forest, thus facilitating pollination);
- Introducing temporal effects (e.g., reducing the size of the forest does not decrease the population of bees immediately, but triggers a gradual decrease in bee population);
- Introducing “special cases” (e.g., the farmer can purchase an artificial beehive and place it in a field of blueberries, but (s)he will have to pay for this (subtracting from the profit).   
- Introducing different bee species with different behaviours

These extensions could potentially be presented to the player as different levels of the game (showcasing the growing complexity of the real-life problem of maximizing profits and maintaining diversity, and helping the player to learn about this complexity through different levels of the game. 

How does it sound?

**Comment by cgmb** [comment]
So, reiterating, the first step is to make this system stateless. Our first profit function will be very simple. Just `profit = countTrees(grid) * countBushes(grid)`. We'll just display that on the screen. No buying bushes. No different types of bees. No turns.

This may impact other contributors as it will strip out a lot of code, but we've put together a clear design that should balance the game. We'll build on top of this with new levels going forwards. At the moment it's too complicated to understand play strategies for designers and players alike.

We'll have all the different levels (rulesets) accessible from the start but encourage them to start at the beginning. When players get a decent level of profit in each level we can prompt them to try the next level of complexity (see Issue #45).

One step back, two steps forwards.

**Comment by cgmb** [comment]
![basic_idea](https://cloud.githubusercontent.com/assets/4886803/7994854/1237aaec-0ace-11e5-9e04-99736b13f937.jpg)

**Comment by cgmb** [comment]
So, we're definitely not there yet, but we're thinking level 2 will use a profit function where the number of forest tiles surrounding a blueberry patch affects the yeild of that blueberry patch. There's a diagram below. See also Issue #53 for further explanation of that level and others.

![level2](https://cloud.githubusercontent.com/assets/4886803/7995251/8a3249aa-0ad1-11e5-91a3-954412050d5e.jpg)

**Comment by cgmb** [comment]
So, we're definitely super-not-there-yet, but here's some thoughts on the profit function for level 3. Again, see Issues #53 for more introduction.

![level3](https://cloud.githubusercontent.com/assets/4886803/7997306/fb5febbc-0ae7-11e5-9d32-3a5ebf63f111.jpg)

**Comment by cgmb** [comment]
The changes have been pretty significant, and we're having a hard enough time just managing coordination between the people in our team in Calgary, so there'd definitely be no hard feelings if anybody in other groups wanted to branch and pursue a different model.

**Comment by ajspadial** [comment]
You are adding features as laws extrated from experimenting.

Another way to go is adding features as small rules (for bees, forest, berry bushes), making a kind of agent-based simulation, and watching how emergent behaviours appear.

The first one will make easier to explain why things are going well or not.

The second one provides an implicit way to model things like spatial structure importance, making easier to model some aspects of the simulation. As a drawback a model running some thousands bees could be slow.

**Comment by cgmb** [comment]
Exploring agent-based modelling would be interesting, but statistical models are easier to visualize directly.

Anyways, it could still use some tune-ups, but I think the goals of this plan have largely been achieved.
