### ISSUE TITLE
sookinoby: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by sookinoby** [jvamosi/Diversibee#44]
I am suresh graduate student in computer science. I love programming in java and javascript.<p><br><blockquote>This issue was created by @sookinoby via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by jvamosi** [comment]
Hi Suresh!

**Comment by sookinoby** [comment]
Hi jana Vamosi.
