### ISSUE TITLE
Painting Forest / Bushes

### ISSUE THREAD

**Issue by cgmb** [jvamosi/Diversibee#46]
Clicking on every tree is slow and annoying. It would be nice if we could click and drag to paint areas as trees or bushes. Maybe just toggling them from one to the other to start off with, but eventually we could add a tool that turns everything into trees and a tool that turns everything into bushes.

**Comment by cgmb** [comment]
I think @ChrissiQ is working on this.

**Comment by ChrissiQ** [comment]
Painting berry bushes, or trees?  Currently we can paint berry bushes.  I don't think they are convertible back to trees right now.

**Comment by ChrissiQ** [comment]
Will wait on a few changes from @arowens before messing with this code.

**Comment by ChrissiQ** [comment]
Solved in 64703337515d4dbce56d18cd037f3753ace7e3e8
