### ISSUE TITLE
Webpage Appearance

### ISSUE THREAD

**Issue by cgmb** [jvamosi/Diversibee#48]
The game board looks reasonably good, but we could use:

- Stylish boarder around the game board
- Better background colour
- Nice font for profits
- Boarder around profits
- Centre the game in the screen

Really, just visual design for the page.

**Comment by sookinoby** [comment]
Can we use bootstrap to give better visual appearance?

**Comment by cgmb** [comment]
I'm not much of a JS dev, but I know bootstrap is popular. What do you think, @ChrissiQ?

**Comment by ChrissiQ** [comment]
Bootstrap would be okay for a quick theme implementation.  I'm always hesitant to recommend bootstrap because they use a lot of conventions that I don't approve of - but it's more familiar and accessible for a lot of people, so it may be a good option then!
