### ISSUE TITLE
Script to explain the game to users

### ISSUE THREAD

**Issue by jvamosi** [jvamosi/Diversibee#53]
Here is some simple statements to explain the game to users. Edit at will:

Level 1:
Imagine you are a farmer wanting to plant blueberries for profit. While it would seem like a good strategy to cut down your forest and plant as many blueberry bushes as possible, the blueberry bushes need bees to pollinate them. No bees, no blueberries to sell! And the bees live in the forest. 

You are greedy and want to make as much profit as possible. How should you configure your plot to make as much money as possible? Click on the tiles to start designing your perfect blueberry farm!

Level 2: 
Good job. You kept some bees alive to ensure a healthy profitable crop. Now see if you can optimize your blueberry crop when the health of the neighboring regions is what determines the blueberries produced by each shrub. Location, location, location!

Level 3:
Well done, farmer. You maintained enough bees to make a profit off of blueberries. In the real world, you also gain benefits from maintaining many bee species. So if you have five pollinator species, your blueberry bushes will do even better than if there was only one. But bees can be sensitive critters that thrive in intact forest patches. Consider that the number of pollinator species in one forest tile depends on how many neighboring cells are in still in the forest state as opposed to crop. Go to it, farmer. Optimize your harvest while keeping your ecosystem healthy. Word.

**Comment by jvamosi** [comment]
Revised text:
Level 1:
You have bought a waste area, containing mostly degraded land and weeds for cheap with the dream of turning it into a profitable blueberry farm. But blueberry bushes need bees to pollinate them. No bees, few blueberries to sell! And the bees live in the forest. What should you plant to maximize your profit?

Level 2: 
Good job. You planted enough trees to have your blueberries pollinated well. The story is more complicated though because bees can only fly so far. A blueberry patch is best pollinated when it is surrounded by forest. Two plots are better than one; three plots are better than two, and so forth up to six (seven or eight make no further difference). Now not only what you plant but where you plant it makes a difference. Try to get the best profit now!

Level 3:
Well done, farmer. You maintained enough bees to make a profit off of blueberries. In the real world, you also gain from maintaining many bee species. So if you have five pollinator species, your blueberry bushes will do even better than if there was only one. But bees can be sensitive critters that thrive in intact forest patches. Consider that the number of pollinator species in one forest patch depends on how many other neighboring patches are in still in the forest state as opposed to crop. The more forest patches surrounding a given one, the more bee species will live there. Go to it, farmer. Optimize your harvest now.

Last statement:
Congratulations! You learned an important lesson. Diversity is good and provides benefits even if you just think of money. ☺

**Comment by cgmb** [comment]
With the exception of the last statement, these have been integrated. That last bit can be done as a part of #45.
