### ISSUE TITLE
Create object for forest,blueberries and grass so new parameter can added to object easily.

### ISSUE THREAD

**Issue by sookinoby** [jvamosi/Diversibee#68]
We can create class for forest, blueberries and grass, and the cells will point to the object of classes. This can help us to add new parameters to model.

**Comment by sookinoby** [comment]
I added a class for TileModel which store basic information on location and type. Can be inherited for forest, blueberries and grass. For forest we can add maturity parameters too.   please know if my issue is valid and I can check in the code.

**Comment by cgmb** [comment]
Aren't cells already class instances? I'm not really a JS guy, but I thought we already had that covered by initializing each cell as a hash table in [generateCell](https://github.com/jvamosi/Diversibee/blob/8f5b07836733eb45fc9e65807f3fda8879af885a/js/stateManagement.js#L36).

**Comment by ChrissiQ** [comment]
Cells are currently just objects - I think @sookinoby wants to inherit the tiles ('cells') from a class to make them consistent.  sookinoby, can we see your code?  Your model may have benefits, but it would be nice to see what you're talking about.

**Comment by sookinoby** [comment]
I am posting the code here.

function TileModel(type,i) {
    this.type = type;
    this.location = location;
}
 
TileModel.prototype.getInfo = function() {
    return this.type + ' ';
};
    
TileModel.prototype.location = function() {
    return this.location + ' ';
};
  
function Forest(type,i,maturation)
{
    TileModel.call(this,i);
    this.maturation = maturation;
}
Forest.prototype = new TileModel();

Forest.prototype.getMaturation = function()
{
    return this.maturation;
    
}

Forest.prototype.increaseMaturation = function()
{
    return this.maturation = this.maturation + 1;
    
}

Now the cell will point to object of forest or blueberry or grass. Each object can have different properties that can be modified.

**Comment by cgmb** [comment]
If there's new development in the future, this design is something to consider. Whoever is doing the work of adding new parameters to the model can decide if they want to do it that way.
