### ISSUE TITLE
reset.css incompatible with bootstrap

### ISSUE THREAD

**Issue by ChrissiQ** [jvamosi/Diversibee#72]
#69 resets bootstrap styles and so is not currently helpful.  If we don't want to use bootstrap, this makes sense.  If we do, it does not.  Bootstrap uses normalize.css to make CSS consistent across browsers - if using it, we shouldn't add reset.css to our code.

It stripped away some of the styles that were making the page quite nice :P

**Comment by cgmb** [comment]
As shown by merging the PR, I don't know anything about bootstrap, but it hasn't gotten in my way. If it would require more work to replace bootstrap than to keep it, we should just revert the PR and move on.

**Comment by ChrissiQ** [comment]
Not a problem, I can fix it later.  Just wanted some reminder to do so :)
