### ISSUE TITLE
Bee Modeling: Migration

### ISSUE THREAD

**Issue by BillMills** [jvamosi/Diversibee#9]
How should bees migrate from forest to forest? The simplest thing would be if there are lots of bees of a given type in one forest tile, but not many in a neighbouring tile, the population could spread out over the region. Some more realistic ideas:

*Swarming* - once a hive reaches a certain size, ~60% of the population breaks off and seeks to colonize elsewhere.  Characteristic of european honeybees.

*Absconding* - An entire bee population migrates to a new location, possibly provoked by worsening conditions in their current home.  Characteristic of africanized bees.

**Comment by cgmb** [comment]
This is a very cool idea. It's pretty fundamentally different from the simplified models we're using, so it would have to go in later levels.

Though, I have a nagging feeling that players might have a difficult time understanding what is happening when the bees migrate, and why it's occurring. You'd need to do something clever to make that obvious.
